package gov.police.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:57:17 BDT 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://ws.police.gov/", name = "PoliceService")
@XmlSeeAlso({ObjectFactory.class})
public interface PoliceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPoliceRecordByNationalId", targetNamespace = "http://ws.police.gov/", className = "gov.police.ws.GetPoliceRecordByNationalId")
    @WebMethod
    @ResponseWrapper(localName = "getPoliceRecordByNationalIdResponse", targetNamespace = "http://ws.police.gov/", className = "gov.police.ws.GetPoliceRecordByNationalIdResponse")
    public gov.police.ws.PoliceRecord getPoliceRecordByNationalId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
