
package gov.ec.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:57:14 BDT 2011
 * Generated source version: 2.3.1
 * 
 */

public final class NIDService_NIDServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.ec.gov/", "NIDServiceImplService");

    private NIDService_NIDServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NIDServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NIDServiceImplService ss = new NIDServiceImplService(wsdlURL, SERVICE_NAME);
        NIDService port = ss.getNIDServiceImplPort();  
        
        {
        System.out.println("Invoking getCitizenByNationalId...");
        java.lang.String _getCitizenByNationalId_arg0 = "";
        gov.ec.ws.Citizen _getCitizenByNationalId__return = port.getCitizenByNationalId(_getCitizenByNationalId_arg0);
        System.out.println("getCitizenByNationalId.result=" + _getCitizenByNationalId__return);


        }

        System.exit(0);
    }

}
