package gov.ncra.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:54:20 BDT 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://ws.ncra.gov/", name = "NCRAService")
@XmlSeeAlso({ObjectFactory.class})
public interface NCRAService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNCRARecordByNationalId", targetNamespace = "http://ws.ncra.gov/", className = "gov.ncra.ws.GetNCRARecordByNationalId")
    @WebMethod
    @ResponseWrapper(localName = "getNCRARecordByNationalIdResponse", targetNamespace = "http://ws.ncra.gov/", className = "gov.ncra.ws.GetNCRARecordByNationalIdResponse")
    public gov.ncra.ws.NcraRecord getNCRARecordByNationalId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
