
package gov.nbr.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:52:15 BDT 2011
 * Generated source version: 2.3.1
 * 
 */

public final class NBRService_NBRServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.nbr.gov/", "NBRServiceImplService");

    private NBRService_NBRServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NBRServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NBRServiceImplService ss = new NBRServiceImplService(wsdlURL, SERVICE_NAME);
        NBRService port = ss.getNBRServiceImplPort();  
        
        {
        System.out.println("Invoking getNBRRecordByNationalId...");
        java.lang.String _getNBRRecordByNationalId_arg0 = "";
        gov.nbr.ws.NbrRecord _getNBRRecordByNationalId__return = port.getNBRRecordByNationalId(_getNBRRecordByNationalId_arg0);
        System.out.println("getNBRRecordByNationalId.result=" + _getNBRRecordByNationalId__return);


        }

        System.exit(0);
    }

}
