package gov.brta.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:55:38 BDT 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://ws.brta.gov/", name = "BRTAService")
@XmlSeeAlso({ObjectFactory.class})
public interface BRTAService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBRTARecordByNationalId", targetNamespace = "http://ws.brta.gov/", className = "gov.brta.ws.GetBRTARecordByNationalId")
    @WebMethod
    @ResponseWrapper(localName = "getBRTARecordByNationalIdResponse", targetNamespace = "http://ws.brta.gov/", className = "gov.brta.ws.GetBRTARecordByNationalIdResponse")
    public gov.brta.ws.BrtaRecord getBRTARecordByNationalId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
