
/*
 * 
 */

package gov.brta.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:55:39 BDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "BRTAServiceImplService", 
                  wsdlLocation = "file:wsdl/brta.wsdl",
                  targetNamespace = "http://ws.brta.gov/") 
public class BRTAServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.brta.gov/", "BRTAServiceImplService");
    public final static QName BRTAServiceImplPort = new QName("http://ws.brta.gov/", "BRTAServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/brta.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/brta.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BRTAServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BRTAServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BRTAServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns BRTAService
     */
    @WebEndpoint(name = "BRTAServiceImplPort")
    public BRTAService getBRTAServiceImplPort() {
        return super.getPort(BRTAServiceImplPort, BRTAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BRTAService
     */
    @WebEndpoint(name = "BRTAServiceImplPort")
    public BRTAService getBRTAServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BRTAServiceImplPort, BRTAService.class, features);
    }

}
