
/*
 * 
 */

package gov.ncra.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 11:03:13 BDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "NCRAServiceImplService", 
                  wsdlLocation = "file:wsdl/ncra.wsdl",
                  targetNamespace = "http://ws.ncra.gov/") 
public class NCRAServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.ncra.gov/", "NCRAServiceImplService");
    public final static QName NCRAServiceImplPort = new QName("http://ws.ncra.gov/", "NCRAServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/ncra.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/ncra.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NCRAServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NCRAServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NCRAServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns NCRAService
     */
    @WebEndpoint(name = "NCRAServiceImplPort")
    public NCRAService getNCRAServiceImplPort() {
        return super.getPort(NCRAServiceImplPort, NCRAService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NCRAService
     */
    @WebEndpoint(name = "NCRAServiceImplPort")
    public NCRAService getNCRAServiceImplPort(WebServiceFeature... features) {
        return super.getPort(NCRAServiceImplPort, NCRAService.class, features);
    }

}
