
/*
 * 
 */

package gov.police.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:41:40 BDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "PoliceServiceImplService", 
                  wsdlLocation = "file:wsdl/police.wsdl",
                  targetNamespace = "http://ws.police.gov/") 
public class PoliceServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.police.gov/", "PoliceServiceImplService");
    public final static QName PoliceServiceImplPort = new QName("http://ws.police.gov/", "PoliceServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/police.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/police.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PoliceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PoliceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PoliceServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns PoliceService
     */
    @WebEndpoint(name = "PoliceServiceImplPort")
    public PoliceService getPoliceServiceImplPort() {
        return super.getPort(PoliceServiceImplPort, PoliceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PoliceService
     */
    @WebEndpoint(name = "PoliceServiceImplPort")
    public PoliceService getPoliceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PoliceServiceImplPort, PoliceService.class, features);
    }

}
