
package gov.police.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Jan 26 10:41:40 BDT 2011
 * Generated source version: 2.3.1
 * 
 */

public final class PoliceService_PoliceServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.police.gov/", "PoliceServiceImplService");

    private PoliceService_PoliceServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PoliceServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PoliceServiceImplService ss = new PoliceServiceImplService(wsdlURL, SERVICE_NAME);
        PoliceService port = ss.getPoliceServiceImplPort();  
        
        {
        System.out.println("Invoking getPoliceRecordByNationalId...");
        java.lang.String _getPoliceRecordByNationalId_arg0 = "";
        gov.police.ws.PoliceRecord _getPoliceRecordByNationalId__return = port.getPoliceRecordByNationalId(_getPoliceRecordByNationalId_arg0);
        System.out.println("getPoliceRecordByNationalId.result=" + _getPoliceRecordByNationalId__return);


        }

        System.exit(0);
    }

}
